export const level7 = [
[
  "Janusz kupił w Biedronce 8 paczek bombek po 12,50 zł każda. Dzięki karcie Moja Biedronka zaoszczędził 3zł. Ile ostatecznie Janusz zapłacił za zakupy?",
  "Grażyna powiesiła na choince 256 lampek, z czego co czwarta była czerwona. Ile czerwonych lampek powiesiła?",
  "Janusz przygotował 15 worków prezentów, z których każdy zawierał 24 paczki. Ile paczek przygotował razem?",
  "Grażyna upiekła 112 pierników i rozdała je 7 sąsiadkom po równo. Ile pierników dostała każda sąsiadka?",
  "Janusz zapakował pierniki w pudełka po 12 sztuk. Jeśli zapakował 96 pierników, ile pudełek zużył?",
  "Grażyna upiekła pierniki w kształcie prostokąta o wymiarach 8 cm × 10 cm. Oblicz, ile cm kwadratowych lukru potrzebuje, by ozdobić jednego pierniczka.",
  "Janusz zorganizował kulig dla swoich bombelków. Przejechał 60 km saniami w ciągu 2 godzin. Z jaką średnią prędkością jechał?",
  "Grażyna ozdobiła świąteczny stół girlandą o długości 3 m, dzieląc ją na kawałki po 0,25 m. Ile kawałków uzyskała?",
  "Grażyna kupiła świąteczny obrus w kształcie kwadratu i chce go obszyć czerwoną nitką. Ile nitki potrzebuje, jeśli krawędź obrusa ma 2 metry?",
  "Janusz rozwiesił 18 światełek w 3 rzędach. Każdy rząd miał tyle samo światełek. Ile było w jednym rzędzie?",
  "Janusz zorientował się, że Wigilia wypada w tym roku we wtorek. W jaki dzień przypadną jego urodziny, które są 10 stycznia?"
],
[
  "Grażyna zawiesiła bombkę na 3/4 wysokości choinki, która mierzy 2,4 m. Na jakiej wysokości znajduje się bombka?",
  "Grażyna wysłała Janusza na zakupy. Na liście napisała: kup mąkę i cukier w stosunku 2:1. Jeśli mąki było 12 kg, ile kupił cukru?",
  "Grażyna udekorowała pierniki posypką. Każdy piernik ważył 40 g, posypka stanowiła 10% masy piernika. Ile ważył piernik z posypką?",
  "W kuchni Grażyna przygotowała ciasto na pierogi, którego masa to 4 kg. 60% masy to mąka. Ile kilogramów mąki użyła?",
  "Janusz i Grażyna ulepili pierogi. Janusz upiekł 240 pierogów, a Grażyna 1/3 tej ilości. Ile pierogów ulepiła Grażyna?",
  "Janusz przygotował dekoracyjny stroik w kształcie rombu o przekątnych 6 cm i 8 cm. Ile centymetrów kwadratowych farby potrzebuje, aby pomalować podstawkę od stroika?",
  "Grażyna szła na pasterkę z prędkością 6 km na godzinę. Ile czasu zajmie jej dojście do kościoła oddalonego od jej bloku o 3 kilometry?",
  "Bombelki Janusza i Grażyny przygotowały kartkę świąteczną o wymiarach 137 mm x 5,2 cm. Czy taka kartka zmieści się do koperty o powierzchni 67,2 mm kwadratowych?",
  "Grażyna losuje bombkę z pudełka z ozdobami, w którym znajduje się 35 bombek czerwonych, 12 złotych i 23 srebrne. Czy prawdopodobieństwo, że wylosowana przez Grażynę bombka będzie czerwona jest większe niż 50%?",
  "Janusz zauważył, że mandarynki w osiedlowym sklepie są o połowę tańsze niż w markecie. Ile kosztują mandarynki z marketu, jeśli w osiedlowym sklepie ich cena wynosi 4,60 zł?"
],
[
  "Grażyna zrobiła 4kg sałatki jarzynowej, w której 15% to ziemniaki. Ile ziemniaków użyła Grażyna do przygotowania sałatki?",
  "Grażyna ugotowała 10 litrów barszczu. Ile szklanek musi przygotować, aby do każdej z nich zmieściło się 200 ml zupy?",
  "Janusz i Grażyna kupili razem 60 pierników, z których Janusz spakował 2/5. Ile prezentów spakowała Grażyna?",
  "Janusz musi zamówić materiał na uszycie czapki Mikołaja w kształcie trójkąta równoramiennego o podstawie 12 cm i wysokości 15 cm. Ile centymetrów kwadratowych materiału potrzebuje Janusz na przód i tył czapki?",
  "Grażyna robiła farsz na pierogi. W tym celu wymieszała kapustę z grzybami w stosunku 3:1. Ile było kapusty, jeśli grzybów było 500 gram?",
  "Grażyna kupiła zestaw herbat w Rossmannie dla swojej szwagierki. Pudełko ma kształt trapezu równoramiennego o bokach 4, 10, 5 i 5 centymetrów. Oblicz, ile papieru będzie musiała zużyć Grażyna, aby obwiązać pudełko ozdobną wstążką.",
  "Święty Mikołaj wyruszył do domu Janusza i Grażyny. Zostało mu 200 kilometrów do pokonania. Ile czasu zajmie mu podróż, jeśli jego sanie lecą z prędkością 1000 km/h?",
  "Grażyna wstawiła świąteczne cynamonki do piekarnika o godzinie 13:27. O której godzinie musi je wyjąć, jeśli będą się piekły 45 minut?",
  "Janusz kupił 318 lasek cukrowych. Czy może rozdzielić je po równo pomiędzy 9 dzieci?",
  "Na pasterce Grażyna zauważyła, że aż 20% ministrantów, czyli 5 chłopców przysypia w trakcie mszy. Ilu ministrantów było w kościele?"
],
[
  "Janusz odśnieżał podjazd. Aby odśnieżyć metr kwadratowy podjazdu potrzebuje 15 minut. Ile zajmie mu odśnieżanie, jeśli podjazd ma kształt prostokąta o bokach 3 metry i 6 metrów?",
  "Grażyna kupiła mandarynki za 35 zł, co stanowiło 7% jej rachunku z Lidla. Ile kosztowały zakupy Grażynki w Lidlu?",
  "Janusz przygotował 3 worki prezentów o masie 24 kg, 30 kg i 36 kg. Jaka jest średnia waga worka?",
  "Janusz pojechał po choinkę do szkółki oddalonej o 30km od domu. Wyszedł o godzinie 10:15. O której godzinie wrócił, jeśli w obie strony jechał z prędkością 60 km/h, ale w drodze powrotnej zatrzymał się na 15-minutowy postój, aby zjeść hot-doga w Żabce?",
  "Grażyna kupiła twaróg na sernik po obniżce 25% i zapłaciła za niego 7,50 zł. Ile kosztował twaróg przed obniżką?",
  "Grażyna zauważyła, że co roku dostaje 2 prezenty więcej niż w poprzednim. Jeśli w zeszłym roku dostała 8 prezentów, to za ile lat dostanie 24 prezenty?",
  "Zbłąkany renifer dotarł w okolice podjazdu Janusza, który właśnie kłócił się z sąsiadem. Przerażony kłótnią i potężnym wąsem Janusza, postanowił uciec do Czech. Biegł z prędkością 30 km/h przez 2 godziny, a następnie zwolnił do 20 km/h i biegł kolejne 3 godziny. Jaką średnią prędkość miał na całej trasie?",
  "Janusz dekoruje pierniki. Dekorowanie jednego pierniczka zajmuje mu 8 minut. Grażyna robi to dwa razy szybciej. Ile czasu zajmie im wspólne dekorowanie 72 pierników?",
  "Janusz zobaczył, że sąsiad kupił nowy dywan. Postanowił więc kupić większy, i zaopatrzył się w prostokątny dywan o wymiarach 3 m  x 4 m, aby położyć go w salonie, który ma powierzchnię 20 metrów kwadratowych. Ile procent podłogi pokoju zakryje dywan?",
  "Janusz zaplanował dekorację domu na mapie w skali 1:200. Jeśli długość świątecznego łańcucha na mapie wynosi 3 cm, ile wynosi długość rzeczywista łańcucha w metrach?"
],
[
  "Grażyna ma o 5 gości wigilijnych więcej niż jej sąsiadka. Ile gości ma sąsiadka, jeśli razem goszczą u siebie 33 osoby?",
  "Janusz, znudzony kazaniem księdza na pasterce przyglądał się rzeźbie pod amboną. Jej autor wykuł na niej datę stworzenia jej: MDCXLVII. W którym roku powstała ta rzeźba?",
  "Janusz założył się z sąsiadem, że znajdzie choinkę wyższą o 25% od jego choinki. Choinka sąsiada ma 1,70 m. Ile centymetrów musi mieć choinka Janusza, aby ten wygrał zakład?",
  "Grażyna pakuje sałatkę jarzynową do prostopadłościennego naczynia o wymiarach 15 cm x 10 cm x 0,5 dm Ile sałatki zmieści się do tego naczynia?",
  "Grażyna postanowiła umyć okna, bo bez tego nie ma Świąt. Obliczyła, że umycie podwójnego okna zajmuje jej 8 minut. Ile czasu zajmie jej umycie okien w całym domu, wiedząc że w sypialni znajduje się okno podwójne, w łazience pojedyncze, a w kuchni i salonie potrójne?",
  "Grażyna przygotowała 24 porcje pierogów z kapustą. Janusz zjadł 1/4 wszystkich pierogów, a następnie Grażyna poczęstowała sąsiadów połową tego, co zostało. Ile pierogów zostało Grażynie?",
  "Janusz miał 90 bombek, z czego 2/5 rozwiesił na choince. Następnie dokupił kolejne 40 bombek i rozwiesił połowę z nich. Ile bombek nie zostało wykorzystanych?",
  "Grażyna i Janusz kupili 120 kilogramów karmy dla piesków i kotków, i postanowili rozdać ją schroniskom w stosunku 2:3:5. Ile kilogramów karmy przypadnie na każde schronisko?",
  "Janusz dorabia u szwagra sprzedając choinki. Pierwszy rodzaj ważył 15 kg, drugi o 50% więcej niż pierwszy, a trzeci dwa razy tyle, co drugi. Jaką masę mają wszystkie rodzaje choinek razem?",
  "Grażyna podczas świątecznych porządków, zakupów i przygotowań codziennie robiła o 10% więcej kroków niż dnia poprzedniego. Pierwszego dnia zrobiła 6000 kroków. Ile kroków zrobiła trzeciego dnia?"
],
  [
 "Janusz zorganizował bitwę na śnieżki ze znienawidzonym sąsiadem. Jego celność wyniosła 80%. Niestety, celność sąsiada była o 10% większa od celności Janusza. Ile wynosi celność sąsiada?",
"Janusz postanowił kupić swojej rodzinie pod choinkę skarpety. W tym celu wybrał się do przedsiębiorstwa skarpetkowego Skar-Pol, w którym za 180 par skarpetek trzeba zapłacić 720 zł. Ile zapłaci za 30 par skarpetek?",
"Janusz, szukając oszczędności obliczył, że przy dzieleniu się opłatkiem zużywa się zaledwie 30% opłatka, a reszta się marnuje. Ile opłatka powinien w tym roku kupić, aby wszystko zużyć i zaopatrzyć się na przyszły rok, wiedząc że dotąd kupował 80g opłatka na jedną Wigilię?",
"Janusz i Grażyna zasiedli przy świątecznym stole, gdzie cała rodzina zawzięcie dyskutuje. 20% kłóci się o politykę, 35% w milczeniu zajada się karpiem, 13% snuje teorie spiskowe o koronawirusie, 30% ogląda Kevina, a 1 osoba przegląda instagrama pod stołem. Ile osób zebrało się na Wigilii u Janusza i Grażyny?",
"Janusz piekł pierniki przez 5 dni. Przez pierwsze 3 dni upiekł łącznie 105 pierników. Ile pierników upiekł w pozostałe dwa dni, jeśli przez całe 5 dni piekł średnio 40 pierników?",
"Janusz pracuje jako kierowca ciężarówki. W ostatni dzień pracy przetransportował 300 kg pierogów w trzech kursach. Jeśli za pierwszym razem przewiózł 2/5 masy, a za drugim 1/3 pozostałej, ile przewiózł w trzecim kursie?",
"Grażyna, która jest przedstawicielką rady miasta ma za zadanie udekorować świątecznymi iluminacjami osiedle. Narysowała więc mapę swojego miasteczka w skali 1:500. Droga między domem Grażyny a kościołem ma długość 5 cm na mapie. Następnie dorysowała ścieżkę do parku, która jest o 2 m krótsza od rzeczywistej odległości między domem a kościołem. Jaką rzeczywistą długość ma ta ścieżka?",
"Grażyna i Janusz jedzą mandarynki. Grażyna zjadła 3 razy więcej mandarynek niż Janusz, ale gdy Janusz zje jeszcze 12, oboje będą mieli zjedzone równą liczbę mandarynek. Ile mandarynek zjadło każde z nich?",
"Grażyna upiekła 50 babeczek i 30 ciastek. Chce podzielić je między gości tak, aby każdy dostał po równo ciastek i babeczek. Jaka jest największa liczba gości, która może otrzymać babeczki i ciastka według planu Grażyny?",
"Janusz usłyszał dzwonek do drzwi. Spodziewał się szwagra, kuzynki z mężem, teściowej, siostry, jej syna i sąsiada, który miał oddać drabinę. Jakie jest prawdopodobieństwo, że za drzwiami czeka mężczyzna?",
]
  ]

  export const level8 = [
    [
      "Janusz kupił w Biedronce 8 paczek bombek po 12,50 zł każda. Dzięki karcie Moja Biedronka zaoszczędził 3 złote. Ile ostatecznie Janusz zapłacił za zakupy?",
      "Grażyna powiesiła na choince 256 lampek, z czego co czwarta była czerwona. Ile czerwonych lampek powiesiła?",
      "Janusz przygotował 15 worków prezentów, z których każdy zawierał 24 paczki. Ile paczek przygotował razem?",
      "Grażyna upiekła 112 pierników i rozdała je 7 sąsiadkom po równo. Ile pierników dostała każda sąsiadka?",
      "Janusz zorganizował kulig dla swoich bombelków. Przejechał 60 km saniami w ciągu 2 godzin. Z jaką średnią prędkością jechał?",
      "Grażyna ozdobiła świąteczny stół girlandą o długości 3 m, dzieląc ją na kawałki po 0,25 m. Ile kawałków uzyskała?  ",
      "Janusz zapakował pierniki w pudełka po 12 sztuk. Jeśli zapakował 96 pierników, ile pudełek zużył?",
      "Grażyna udekorowała pierniki posypką. Każdy piernik ważył 40 g, posypka stanowiła 10% masy piernika. Ile ważył piernik z posypką?",
      "Janusz rozwiesił 18 światełek w 3 rzędach. Każdy rząd miał tyle samo światełek. Ile było w jednym rzędzie?",
      "Grażyna upiekła pierniki w kształcie prostokąta o wymiarach 8 cm × 10 cm. Oblicz, ile cm kwadratowych lukru potrzebuje, by ozdobić jednego pierniczka.",
    ],
    [
      "Grażyna zawiesiła bombkę na 3/4 wysokości choinki, która mierzy 2,4 m. Na jakiej wysokości znajduje się bombka?",
      "Grażyna wysłała Janusza na zakupy. Na liście napisała: kup mąkę i cukier w stosunku 3:2. Jeśli mąki było 12 kg, ile kupił cukru?  ",
      "Grażyna kupiła świąteczny obrus w kształcie koła i chce go obszyć czerwoną nitką. Ile nitki potrzebuje, jeśli średnica obrusa to 2 metry?",
      "W kuchni Grażyna przygotowała ciasto na pierogi, którego masa to 4 kg. 60% masy to mąka. Ile kilogramów mąki użyła?  ",
      "Janusz i Grażyna ulepili pierogi w stosunku 5:2. Janusz upiekł 240 pierogów. Ile pierogów ulepiła Grażyna? ",
      "Janusz przygotował dekoracyjny stroik w kształcie koła o promieniu 40 cm. Ile centymetrów kwadratowych farby potrzebuje, aby pomalować podstawkę od stroika?  ",
      "Grażyna kupiła mandarynki za 35 zł, co stanowiło 7% jej rachunku z Lidla. Ile kosztowały zakupy Grażynki w Lidlu? ",
      "Bombelki Janusza i Grażyny przygotowały kartkę świąteczną o wymiarach 137 mm x 5,2 cm. Czy taka kartka zmieści się do koperty o powierzchni 67,2 mm kwadratowych?",
      "Grażyna losuje bombkę z pudełka z ozdobami, w którym znajduje się 35 bombek czerwonych, 12 złotych i 23 srebrne. Jakie jest prawdopodobieństwo, że wylosowana przez Grażynę bombka będzie czerwona?",
      "Janusz zorientował się, że Wigilia wypada w tym roku we wtorek. W jaki dzień przypadną jego urodziny, które są 10 stycznia?",
    ],
    [
      "Janusz odśnieżał podjazd w kształcie kwadratu o przekątnej 14 cm. Oblicz powierzchnię podjazdu Janusza.",
      "Grażyna szła na pasterkę z prędkością 6 km na godzinę. Ile czasu zajmie jej dojście do kościoła oddalonego od jej bloku o 1,5 kilometra?",
      "Janusz chciał upiec pierniki w kształcie serca. Niestety w piekarniku ciasto rozlało się i pierniki przybrały kształt trójkąta równobocznego o boku 8 cm. Oblicz pole jednego piernika.",
      "Grażyna zrobiła 4kg sałatki jarzynowej, w której 15% to ziemniaki. Ile ziemniaków użyła Grażyna do przygotowania sałatki?",
      "Janusz usłyszał dzwonek do drzwi. Spodziewał się szwagra, kuzynki z mężem, teściowej, siostry, jej syna i sąsiada, który miał oddać drabinę. Jakie jest prawdopodobieństwo, że za drzwiami czeka mężczyzna?",
      "Grażyna ugotowała 10 litrów barszczu. Ile szklanek musi przygotować, aby do każdej z nich zmieściło się 200 ml zupy?",
      "Janusz i Grażyna kupili razem 60 prezentów, z których Janusz spakował 2/5. Ile prezentów spakowała Grażyna?  ",
      "Grażyna ma o 5 gości wigilijnych więcej niż jej sąsiadka. Ile gości ma sąsiadka, jeśli razem goszczą u siebie 33 osoby?",
      "Janusz, znudzony kazaniem księdza na pasterce przyglądał się rzeźbie pod amboną. Jej autor wykuł na niej datę stworzenia jej: MDCXLVII. W którym roku powstała ta rzeźba?",
      "Janusz założył się z sąsiadem, że znajdzie choinkę wyższą o 25% od jego choinki. Choinka sąsiada ma 1,70 m. Ile centymetrów musi mieć choinka Janusza, aby ten wygrał zakład? ",
    ],
    [
      "Janusz przygotował 3 worki prezentów o masie 24 kg, 30 kg i 36 kg. Jaka jest średnia waga worka?",
      "Grażyna pakuje sałatkę jarzynową do prostopadłościennego naczynia o wymiarach 15 cm x 10 cm x 0,5 dm Ile sałatki zmieści się do tego naczynia? ",
      "Janusz musi zamówić materiał na uszycie czapki Mikołaja w kształcie trójkąta równoramiennego o podstawie 12 cm i ramieniu 10 cm. Ile centymetrów kwadratowych materiału potrzebuje Janusz na przód i tył czapki?",
      "Janusz pojechał po choinkę do szkółki oddalonej o 30km od domu. Wyszedł o godzinie 10:15. O której godzinie wrócił, jeśli w obie strony jechał z prędkością 60 km/h, ale w drodze powrotnej zatrzymał się na 15-minutowy postój, aby zjeść hot-doga w Żabce?",
      "Grażyna robiła farsz na pierogi. W tym celu wymieszała kapustę z grzybami w stosunku 3:1. Ile było kapusty, jeśli grzybów było 500 gram? ",
      "Janusz zorganizował bitwę na śnieżki ze znienawidzonym sąsiadem. Jego celność wyniosła 80%. Niestety, celność sąsiada była o 10% większa od celności Janusza. Ile wynosi celność sąsiada?",
      "Grażyna kupiła zestaw herbat w Rossmannie dla swojej szwagierki. Pudełko ma kształt trapezu równoramiennego o bokach 4, 10, 5 i 5 centymetrów. Oblicz, ile papieru będzie musiała zużyć Grażyna, aby obkleić pudełko ozdobnym papierem.",
      "Grażyna postanowiła umyć okna, bo bez tego nie ma Świąt. Obliczyła, że umycie podwójnego okna zajmuje jej 8 minut. Ile czasu zajmie jej umycie okien w całym domu, wiedząc że w sypialni znajduje się okno podwójne, w łazience pojedyncze, a w kuchni i salonie potrójne?",
      "Janusz postanowił kupić swojej rodzinie pod choinkę skarpety. W tym celu wybrał się do przedsiębiorstwa skarpetkowego Skar-Pol, w którym za 180 par skarpetek trzeba zapłacić 720 zł. Ile zapłaci za 30 par skarpetek?",
      "Janusz, szukając oszczędności obliczył, że przy dzieleniu się opłatkiem zużywa się zaledwie 30% opłatka, a reszta się marnuje. Ile opłatka powinien w tym roku kupić, aby wszystko zużyć i zaopatrzyć się na przyszły rok, wiedząc że dotąd kupował 80g opłatka na jedną Wigilię?",
    ],
    [
      "Grażyna przygotowała 24 porcje pierogów z kapustą. Janusz zjadł 1/4 wszystkich pierogów, a następnie Grażyna poczęstowała sąsiadów połową tego, co zostało. Ile pierogów zostało Grażynie?",
      "Janusz rozwieszał lampki na poddaszu, na ścianie w kształcie trójkąta prostokątnego o wysokości 1,2 m i szerokości 5 m. Ile metrów lampek potrzebuje, aby przyczepić lampki wzdłuż sufitu?",
      "Grażyna włożyła do paczek świątecznych cukierki. W jednej paczce były 3 razy więcej cukierków niż w drugiej. Ile cukierków było w każdej paczce, jeśli łącznie było w nich 56 cukierków?",
      "Grażyna i Janusz pakują prezenty. W czasie, gdy Janusz zapakuje 3 paczki, Grażyna zdąży zapakować 5. Ile paczek zapakuje każde z nich w ciągu godziny, jeśli razem spakowali 64 paczki?",
      "Janusz zorientował się, że sąsiad ma dwie choinki. Nie mógł być gorszy, więc postanowił przygotować trzy różnej wielkości świąteczne choinki. Stosunek wysokości tych choinek wynosi 2:3:4, a ich łączna wysokość to 18 m. Oblicz wysokość każdej z choinek",
      "Janusz i Grażyna zasiedli przy świątecznym stole, gdzie cała rodzina zawzięcie dyskutuje. 20% kłóci się o politykę, 35% w milczeniu zajada się karpiem, 13% snuje teorie spiskowe o koronawirusie, 30% ogląda Kevina, a 1 osoba przegląda instagrama pod stołem. Ile osób zebrało się na Wigilii u Janusza i Grażyny?",
      "Grażyna kupiła twaróg na sernik po obniżce 25% i zapłaciła za niego 7,50 zł. Ile kosztował twaróg przed obniżką?  ",
      "Janusz postanowił powiesić lampki dookoła klonu, który rośnie przed jego domem. Drzewo ma średnicę 2,5 metra. Czy wystarczy mu łańcuch lampek o długości 5 metrów?",
      "Grażyna poszła zrobić sobie świąteczne paznokcie. Niestety, na miejscu okazało się, że cena wzrosła aż o 24%. Ile zapłaciła Grażyna, jeśli dotąd kosztowało ją to 70 złotych? Wynik zaokrąglij do pełnych złotówek.",
      "Janusz piekł pierniki przez 5 dni. Przez pierwsze 3 dni upiekł łącznie 105 pierników. Ile pierników upiekł w pozostałe dwa dni, jeśli przez całe 5 dni piekł średnio 40 pierników?",
    ],
    [
      "Janusz musiał odebrać z lotniska rodzinę, która przyleciała na święta zza granicy. Droga zajęła mu 3,5 godziny i pokonał ją z prędkością 80 km/h. Ile litrów benzyny musi zatankować, jeśli jego samochód spala średnio 9 litrów na 100 km?",
      "Janusz owijał pudełko prezentowe w kształcie prostopadłościanu o wymiarach 8 cm × 10 cm × 12 cm. Ile papieru do pakowania będzie potrzebował, aby pokryć całe pudełko?",
      "Grażyna i Janusz chcieli posadzić gości przy prostokątnym stole o wymiarach 4 m × 3 m, lecz nie był on wystarczająco duży. Zdecydowali się więc dostawić wzdłuż dłuższego boku drugi stół w kształcie półkola o średnicy 4 m. Oblicz powierzchnię obrusa, jaki należy położyć na połączonych stołach.",
      "Janusz stworzył miniaturową makietę choinki o wysokości 12 cm. Prawdziwa choinka ma 4 m wysokości. W jakiej skali została wykonana makieta?",
      "Grażyna zauważyła, że co roku dostaje 2 prezenty więcej niż w poprzednim. Jeśli w zeszłym roku dostała 8 prezentów, to za ile lat dostanie 24 prezenty?",
      "Janusz spędził dwukrotnie więcej czasu na pakowanie dużych prezentów niż na pakowanie małych. Gdyby spędził o 5 minut mniej na małych prezentach, czas na pakowanie dużych byłby trzykrotnie większy. Ile czasu spędził na pakowanie dużych i małych prezentów?",
      "Janusz zrobił dwie części girlandy: jedną w kolorze czerwonym, drugą w kolorze złotym. Girlanda w kolorze czerwonym jest o 5 m krótsza niż trzy czwarte długości złotej girlandy. Łącznie obie girlandy mają długość 25 m. Jaką długość ma każda girlanda?",
      "Grażyna, która jest przedstawicielką rady miasta ma za zadanie udekorować świątecznymi iluminacjami osiedle. Narysowała więc mapę swojego miasteczka w skali 1:500. Droga między domem Grażyny a kościołem ma długość 5 cm na mapie. Następnie dorysowała ścieżkę do parku, która jest o 2 m krótsza od rzeczywistej odległości między domem a kościołem. Jaką rzeczywistą długość ma ta ścieżka?",
      "Grażyna i Janusz przygotowali 100 paczek karmy dla piesków i kotków, które podzielili między trzy schroniska, które postanowili wesprzeć z okazji świąt. Pierwsze schronisko otrzyma 10 paczek więcej niż drugie, a trzecie dwa razy więcej niż pierwsze. Ile paczek otrzyma każde schronisko?",
      "Janusz pracuje jako kierowca ciężarówki. W ostatni dzień pracy przetransportował 300 kg pierogów w trzech kursach. Jeśli za pierwszym razem przewiózł 2/5 masy, a za drugim 1/3 pozostałej, ile przewiózł w trzecim kursie?",
    ]
  ]